import { useState,useEffect } from 'react'
import Footer from './components/Footer'
import Head from 'next/head'
import Main from './components/Main'
import About from './components/About'
import Works from './components/Works'
import Contact from './components/Contact'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Portfolio | Tushar Gautam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Works/>
      <Contact/>
    </div>
  )
}
